### ISSUE TITLE
Not working for University Stuttgart

### ISSUE THREAD

**Issue by henning410** [Viperinius/ILIAS-Sync2Folder#1]
Hello, It's not working for University Stuttgart. Why not? Is this feature coming? 
Greetings

**Comment by Viperinius** [comment]
As stated on the university page, the SOAP service for students has been disabled. The tool uses SOAP to connect to ILIAS, so it does not work there.

It would probably be possible to establish a connection via detours, but would require a complete new structure of the programme.
